exp_type: 'ssc'
strategy: 'gem'

dataroot: '/data/cossu/speech_words'
result_folder: '/data/cossu/experiments/ssc/gem_lstm'
assess_runs: 5

use_rnn: true
rnn_units: 512

no_ray: false
max_cpus: 50
cpus_per_job: 3
cuda: true
max_gpus: 2
gpus_per_job: 0.25

### OPTIMIZER
learning_rate: 1e-3
epochs: 30
batch_size: 128
opt_name: 'adam'

patterns_per_exp: 256
strength: 1

## GRID SEARCH
grid:
  patterns_per_exp:
    - 256
    - 512
  strength:
    - 0
    - 0.5
    - 1

